### ISSUE TITLE
Бот, корректировка меню

### ISSUE THREAD

**Issue by robky** [Studio-Yandex-Practicum/together-for-life#22]
При получении "секретного слова" от админа  бот выводит наименование меню (нулевым пунктом стартовое сообщение) и ниже меню с цифрами в одну линию, но чтобы не путаться с обычным выводом добавить какой-нибудь символ, например:

`[E0][E1][E2][E3][E4][E5][E6][E7]`

[E0] - это стартовое сообщение

После выбора пользователем пункта, спросить что меняем [Заголовок] или [Информацию]

**Comment by floks41** [comment]
Беру задачу.
