### ISSUE TITLE
Изменить поведение на старте

### ISSUE THREAD

**Issue by robky** [Studio-Yandex-Practicum/together-for-life#34]
В самом начале взаимодействия бот здоровается, рассказывает о себе и заканчивает фразой "Чем мы можем помочь именно вам?"

Пользователь видит ниже окно для ввода и клавиатуру [Меню]. Создается впечатление что от пользователя ждут что он что-то напишет, но в ответ он получит тоже самое. Если у нас единственный маршрут это меню, то предлагаю после фразы "Чем мы можем помочь именно вам?" сразу вывести текстовое меню и ниже "Выберите цифру пункта меню" и ниже клавиатура с цифрами меню.

**Comment by miscanth** [comment]
Беру
